#encoding=UTF-8
print '==={:<10}==='.format('ok')
print '==={:_<10}==='.format('ok')
print '==={:*<10}==='.format('ok')
print '==={:\'<10}==='.format('ok')
print '==={:"<10}==='.format('ok')
print '==={:^>10}==='.format('ok')
print '==={:^^10}==='.format('ok')
print '==={:.6}==='.format('okokokokokokok')
print '===%.6s==='%('okokokokokokok')
print '==={:.6}==='.format('這是中文的內容')
print '===%.6s==='%('這是中文的內容')